### ISSUE TITLE
ハンバーガーメニュー内押しても消えない

### ISSUE THREAD

**Issue by Tsuyoshi-I** [Tsuyoshi-I/cvlp-v2#46]
pull request中

**Comment by Tsuyoshi-I** [comment]
スマホ時のメニューを押した時にメニューを閉じる機能

**Comment by taiki-fw** [comment]
6/22(土)現在のmasterブランチでhttp-serverの挙動
- transform: translateが効いていない
- メニューないのaタグを押したら移動する
