### ISSUE TITLE
生徒の声下層

### ISSUE THREAD

**Issue by Tsuyoshi-I** [Tsuyoshi-I/cvlp-v2#51]
現LPからベタ張りしただけなので、細かい調整はまだ見られていません

**Comment by taiki-fw** [comment]
修正点
- ダウンロードページ
  - 現状[html,php] 
  - 変更後[php]

- 生徒の声
   - prev, nextボタンのレスポンシブでのスタイルの崩れ

- カリキュラム下層
   - 現状formがお問い合わせページ
   - 変更後formのactionをdownload.phpとする

**Comment by taiki-fw** [comment]
ダウンロードページとカリキュラム下層は同じ修正なので他のissueに移行します
